
version: 2
jobs:
  build:
    macos:
      xcode: "11.3.0"
      # cmake: "3.16.2"
      # node: "10.18.0"
      # python: "3.7.3"
      # npm: "6.13.4"
    steps:
      - checkout
      - run:
        name: install homebrew
        command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run:
        name: install build cmake and node@10
        command: brew install cmake node@10 npm
      - run:
        name: install pipenv
        command: python3 -m pip install pipenv
      - run:
        name: install build tools
        command: npm install -g yarn electron-builder
      - run:
        name: build app
        command: yarn && yarn build
      - run:
        name: package
        command: zip -r kungfu-macos.zip app/build
      - store_artifacts:
        path: kungfu-macos.zip
        destination: app